version: '3.8'
services:
  stock-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data/kline-data:/data
      - ./public:/app/public  # 如果需要保存截图等文件
    environment:
      - FLASK_ENV=production
      - DATA_FOLDER=/data
    restart: unless-stopped